name: Install Dependencies
runs:
  using: composite
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.4
      with:
        node-version: 20.12.2

    - name: Install dependencies
      run: npm install
      shell: bash
