name: Angular CI
on: [push]
jobs:
  angular-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20.12.2

      - name: Install dependencies
        run: npm install

      - name: Execute unit tests
        run: npm run test
