name: Angular CI
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Execute unit tests
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        if: success()
        run: npm run build

  deploy:
    needs:
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: npm run build -- --base-href=/${{ github.event.repository.name }} --deploy-url=/${{ github.event.repository.name }}/

      - name: Setup Pages
        if: success()
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: success()
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist/angular-ci/browser"

      - name: Deploy to GitHub Pages
        if: success()
        uses: actions/deploy-pages@v4

      - name: Show
        run: cat ./dist/angular-ci/browser/index.html
